### PR TITLE
additional fixture for #90

### PR DESCRIPTION
**Pull request by EamonHetherton**

### CODE REVIEW

**Comment by hazzik** [comment]
@EamonHetherton it's because it uses an older version.

**Comment by EamonHetherton** [comment]
I realise that NHibernate uses an older version, but the PR and comment reflects some additional unnecessary changes that the newest version 0.11.0 adds.  Specifically, it adds the ""catch (OperationCanceledException) { throw; }" even when the containing try block does not call async code.

**Comment by EamonHetherton** [comment]
@hazzik BTW, this is in a effort to fix GH1672 in NHibernate

**Comment by maca88** [comment]
I've added an additional logic that will add the catch block only if there is an async invocations inside the `try` statement block that uses a cancellation token as an argument or a cancellation token guard is added.

**Comment by hazzik** [comment]
But any method can just throw OperationCanceledException without a reason. I think it would be much safer to add the catch regardless if there are signs of using the cancellation logic or not.

**Comment by EamonHetherton** [comment]
But if existing code is already throwing an OperationCanceledException, should it not already contain a catch block for OperationCanceledException? I guess my thinking is that the AsyncGenerator should add a catch block for OperationCanceledException only when it has introduced a new code path that might throw one, otherwise it should try to preserve existing behavior.

**Comment by maca88** [comment]
> I think it would be much safer to add the catch regardless if there are signs of using the cancellation logic or not

An async method with a cancellation can throw an `OperationCanceledException` by calling `cancellationToken.ThrowIfCancellationRequested()`, which cannot happen in the synchronous version of the method. The point of adding the `OperationCanceledException` catch block is handle this specific. If we have an async method that throws an `OperationCanceledException` without having a cancellation token then this throw statement will be also in the synchronous version of the method. Example:

Original method:
```
public void Test(Func<bool> isCancelled) {
  try {
    if (isCancelled()) {
      throw new OperationCanceledException("");
    }
    File.ReadFile("");
  }
  catch (Exception e) {
    throw new CustomException("Custom exception", e)
  }
}
```
Async version:
```
public async Task TestAsync(Func<bool> isCancelled) {
  try {
    if (isCancelled()) {
      throw new OperationCanceledException("");
    }
    await File.ReadFileAsync("");
  }
  catch (Exception e) {
    throw new CustomException("Custom exception", e)
  }
}
```
If we would add the `OperationCanceledException` catch block to the async version, the exception when the `OperationCanceledException` would be thrown will not be the same.

**Comment by maca88** [comment]
> I guess my thinking is that the AsyncGenerator should add a catch block for OperationCanceledException only when it has introduced a new code path that might throw one, otherwise it should try to preserve existing behavior.

I think the same.

**Comment by hazzik** [comment]
Ok

**Pull request merged**
