### PR TITLE
NH: Always generate default parameter for CancellationToken

### PR DESCRIPTION
**Pull request by hazzik**
I need to decide what's the best options to do now, so will stick with default parameters for everything for now.

The rules I have in mind now:

- User called interfaces (ISession, IQuery, IQueryOver, ICriteria, etc) - generate default parameter
- Framework called interfaces (IXXXEventListener, IVersionType, etc) - generate parameter
- **Interface rules shall be passed to implementors**

### CODE REVIEW

**Comment by hazzik** [comment]
Please do not merge yet, I'll be updating the PR with the desired rules.

**Comment by maca88** [comment]
> Interface rules shall be passed to implementors

Will check what I can do here.

**Comment by maca88** [comment]
I updated the `MethodGeneration` option so that the mentioned rules can be easier met. [Here](https://github.com/maca88/AsyncGenerator/blob/master/Source/AsyncGenerator.Tests/ExternalProjects/NHibernate/Fixture.cs#L46) you can see how to apply the new rules.

**Comment by hazzik** [comment]
@maca88 I've updated the PR with the desired state. So, basically everything which is root namespace and 3 classes in hbm2dll tool.

**Pull request merged**
