### PR TITLE
Add simple console runner.

### PR DESCRIPTION
**Pull request by hazzik**

### CODE REVIEW

**Comment by hazzik** [comment]
@maca88 can you make this available on NuGet, so we can start build tooling around?

**Comment by maca88** [comment]
Will publish on NuGet in the following days. Also, I will try to find a way to make it work on .NetStandard prior publishing.

**Comment by hazzik** [comment]
I would personally like to see the NuGet first, and netstandard somewhere in the feature.

**Comment by maca88** [comment]
Ok, will do so.

**Comment by maca88** [comment]
Now the generator is available on [Nuget](https://www.nuget.org/packages?q=CSharpAsyncGenerator).

**Comment by hazzik** [comment]
:hooray:

**Comment by hazzik** [comment]
:fireworks: :champagne:

**Pull request merged**
