### PR TITLE
WIP - Support for Mono

### PR DESCRIPTION
**Pull request by maca88**
Fix tests for:
- [x] IfDirective
- [x] MissingMembers
- [x] PartialCompilation
- [x] RegionDirective

### CODE REVIEW

**Comment by maca88** [comment]
The above tests are failing because Roslyn adds a [CarriageReturnLineFeed](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/CSharp/Portable/Syntax/SyntaxNodeRemover.cs#L108), instead of LineFeed, when running on Unix.

**Comment by hazzik** [comment]
Why do we need msbuild 15.5?

**Comment by maca88** [comment]
> Why do we need msbuild 15.5?

In order to avoid [GetEnvironmentStrings](https://github.com/maca88/AsyncGenerator/pull/62#issue-267856690) error on non Windows platforms. They have added [a check](https://github.com/Microsoft/msbuild/blob/804e1f1a6914350993bed704e29d65a3f8513ebb/src/Shared/CommunicationsUtilities.cs#L159) to call `GetEnvironmentStrings` only if running on Windows.

**Comment by maca88** [comment]
With the latest commit we can generate async code for NHibernate on non Windows platforms. The only thing that needs to be changed is the directory separator in the configuration. In order the generator to work consistently on various platforms the slash (`/`) directory separator shall be used instead of a backslash (`\`).

**Comment by maca88** [comment]
This PR will be included in the next release. The CommandLine nuget will contain MSBuild 15.5 preview package, that contains also the optimizations explained [here](https://github.com/maca88/AsyncGenerator/issues/58).

**Pull request merged**
