### PR TITLE
Add support for .NET Core 3.1.200

### PR DESCRIPTION
**Pull request by maca88**
WIP until Roslyn `3.6.0` is released. With version `3.5.0` tests fail on linux and osx and the fix was released in version [3.6.0-3.20181.5](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis/3.6.0-3.20181.5).

### CODE REVIEW

**Comment by hazzik** [comment]
@maca88 3.6.0 has been released :)

**Comment by maca88** [comment]
I completely forgot about it, thanks for remaining me :) I updated it to 3.7.0, but unfortunatelly it does not work with .NET 5, throws the following exception:
```
System.InvalidOperationException : One or more errors occurred while opening the project:
Msbuild failed when processing the file 'C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator.Tests\AsyncGenerator.Tests.csproj' with message: The SDK resolver type "WorkloadSdkResolver" failed to load. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.  C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator.Tests\AsyncGenerator.Tests.csproj
Hint: For suppressing irrelevant errors use SuppressDiagnosticFailures option.
  Stack Trace:
     at AsyncGenerator.AsyncCodeGenerator.CheckForErrors(MSBuildWorkspace workspace, String itemType, ImmutableArray`1 supressFailuresPredicates, ILogger logger) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator\AsyncCodeGenerator.cs:line 436
   at AsyncGenerator.AsyncCodeGenerator.OpenProject(MSBuildWorkspace workspace, String filePath, ImmutableArray`1 supressFailuresPredicates, ILogger logger, CancellationToken cancellationToken) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator\AsyncCodeGenerator.cs:line 375
   at AsyncGenerator.Tests.BaseFixture.OpenProject() in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator.Tests\BaseFixture.cs:line 280
   at AsyncGenerator.Tests.BaseFixture.SetupAndGetReadOnlyProjectAndSolution() in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator.Tests\BaseFixture.cs:line 292
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at AsyncGenerator.Tests.BaseFixture.YamlReadonlyTest(String fileName, String yamlConfig, Action`1 action) in C:\Workspace\Git\AsyncGenerator\Source\AsyncGenerator.Tests\BaseFixture.cs:line 122
   at NUnit.Framework.Internal.ExceptionHelper.Rethrow(Exception exception)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
```
I will have to dig deeper to understand the issue and what can be done to fix it.

**Comment by hazzik** [comment]
@maca88 but if you build it as .NET 5 it probably should work.

**Comment by maca88** [comment]
Your are right, adding the `net5.0` target framework was enough. I will make a separate PR for it.

**Pull request merged**
